######################################################################
# Automatically generated by qmake (3.0) Fri Mar 1 15:50:24 2013
######################################################################

TEMPLATE = app
TARGET = helloqtfoobar
DEPENDPATH += . ../../include
INCLUDEPATH += . ../../lib

# Input
SOURCES += main.cpp
